// <auto-generated />
using LoginOgInfo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoginOgInfo.Migrations
{
    [DbContext(typeof(LoginOgInfoContext))]
    [Migration("20190524173607_ParkeringInfo")]
    partial class ParkeringInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoginOgInfo.BrugerParkering.ParkeringsInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nummerplade");

                    b.HasKey("ID");

                    b.ToTable("ParkeringsInfo");
                });

            modelBuilder.Entity("LoginOgInfo.Lokaler.LokalerInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lejer")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Lokalenummer")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Medarbejderantal")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("LokalerInfo");
                });

            modelBuilder.Entity("LoginOgInfo.Medarbejdere.MedarbejderInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Lokale")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Stilling")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Virksomhed")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("MedarbejderInfo");
                });

            modelBuilder.Entity("LoginOgInfo.Virksomheder.VirksomhederInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVR")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Findvej")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Lokale")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Medarbejdere")
                        .IsRequired()
                        .HasMaxLength(999);

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("VirksomhederInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
